{
 "title": "Aircraft Engine Alert Dashboard",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Stability Monitoring - Ratio of fuel flow to Ps30",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(DateTime),\n  Actual,\n  Pred,\n  LCL,\n  UCL\nFROM\n  sgf_time_series_database\nWHERE\n  $__timeFilter(DateTime) and UCL > 5\n"
    }
   ]
  },
  {
   "title": "Engine Alerts",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  idalert,\n  $__time(DateTime),\n  engineid,\n  fuel_actual,\n  fuel_pred,\n  fuel_ucl_threshold\nFROM\n  sgf_alert_database\nWHERE $__timeFilter(DateTime)\nORDER BY datetime desc\nLIMIT 10\n"
    }
   ]
  },
  {
   "title": "Corrected Core Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(DateTime),\n  Corrected_core_speed\nFROM\n  sgf_time_series_database\nWHERE\n  $__timeFilter(DateTime) and UCL > 5"
    }
   ]
  },
  {
   "title": "HPC Outlet - Total Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(DateTime),\n  Total_pressure_at_HPC_outlet\nFROM\n  sgf_time_series_database\nWHERE\n  $__timeFilter(DateTime) and UCL > 5"
    }
   ]
  },
  {
   "title": "Bypass Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(DateTime),\n  Bypass_ratio\nFROM\n  sgf_time_series_database\nWHERE\n  $__timeFilter(DateTime) and UCL > 5"
    }
   ]
  }
 ]
}